In [1]:
import glob
import pandas as pd

# **Reading Files**

In [2]:
documents = glob.glob('D:\\FCI\\Information Retrieval\\dataset\\BBC text classification\\bbc\\business\\*.txt')
documents.extend(glob.glob('D:\\FCI\\Information Retrieval\\dataset\\BBC text classification\\bbc\\entertainment\\*.txt'))
documents.extend(glob.glob('D:\\FCI\\Information Retrieval\\dataset\\BBC text classification\\bbc\\politics\\*.txt'))
documents.extend(glob.glob('D:\\FCI\\Information Retrieval\\dataset\\BBC text classification\\bbc\\sport\\*.txt'))
documents.extend(glob.glob('D:\\FCI\\Information Retrieval\\dataset\\BBC text classification\\bbc\\tech\\*.txt'))

In [3]:
df = pd.DataFrame(documents, columns = ['document'])

In [4]:
#documents = glob.glob('D:/FCI/Information Retrieval/dataset/project dataset/*.txt')
#df = pd.DataFrame(documents, columns = ['document'])

In [5]:
docs = []

In [6]:
for i in range(514):
    print(f'i = {i}')
    input_str=""
    doc = df.iat[i,0]
    with open(doc, "r", encoding='utf-8') as f:
        for word in f.read():
            input_str = input_str + word
        docs.append(input_str.lower())

i = 0
i = 1
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
i = 8
i = 9
i = 10
i = 11
i = 12
i = 13
i = 14
i = 15
i = 16
i = 17
i = 18
i = 19
i = 20
i = 21
i = 22
i = 23
i = 24
i = 25
i = 26
i = 27
i = 28
i = 29
i = 30
i = 31
i = 32
i = 33
i = 34
i = 35
i = 36
i = 37
i = 38
i = 39
i = 40
i = 41
i = 42
i = 43
i = 44
i = 45
i = 46
i = 47
i = 48
i = 49
i = 50
i = 51
i = 52
i = 53
i = 54
i = 55
i = 56
i = 57
i = 58
i = 59
i = 60
i = 61
i = 62
i = 63
i = 64
i = 65
i = 66
i = 67
i = 68
i = 69
i = 70
i = 71
i = 72
i = 73
i = 74
i = 75
i = 76
i = 77
i = 78
i = 79
i = 80
i = 81
i = 82
i = 83
i = 84
i = 85
i = 86
i = 87
i = 88
i = 89
i = 90
i = 91
i = 92
i = 93
i = 94
i = 95
i = 96
i = 97
i = 98
i = 99
i = 100
i = 101
i = 102
i = 103
i = 104
i = 105
i = 106
i = 107
i = 108
i = 109
i = 110
i = 111
i = 112
i = 113
i = 114
i = 115
i = 116
i = 117
i = 118
i = 119
i = 120
i = 121
i = 122
i = 123
i = 124
i = 125
i = 126
i = 127
i = 128
i = 129
i = 130
i = 131
i = 132
i = 133
i = 134
i = 135
i = 136
i = 137
i = 13

# **Tokenization**

In [7]:
import nltk
from nltk.tokenize import  word_tokenize

In [8]:
tokens=[]

In [9]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [10]:
for i in range(514):
    tokens.append(word_tokenize(docs[i]))

In [11]:
tokens[0]

['ad',
 'sales',
 'boost',
 'time',
 'warner',
 'profit',
 'quarterly',
 'profits',
 'at',
 'us',
 'media',
 'giant',
 'timewarner',
 'jumped',
 '76',
 '%',
 'to',
 '$',
 '1.13bn',
 '(',
 '£600m',
 ')',
 'for',
 'the',
 'three',
 'months',
 'to',
 'december',
 ',',
 'from',
 '$',
 '639m',
 'year-earlier',
 '.',
 'the',
 'firm',
 ',',
 'which',
 'is',
 'now',
 'one',
 'of',
 'the',
 'biggest',
 'investors',
 'in',
 'google',
 ',',
 'benefited',
 'from',
 'sales',
 'of',
 'high-speed',
 'internet',
 'connections',
 'and',
 'higher',
 'advert',
 'sales',
 '.',
 'timewarner',
 'said',
 'fourth',
 'quarter',
 'sales',
 'rose',
 '2',
 '%',
 'to',
 '$',
 '11.1bn',
 'from',
 '$',
 '10.9bn',
 '.',
 'its',
 'profits',
 'were',
 'buoyed',
 'by',
 'one-off',
 'gains',
 'which',
 'offset',
 'a',
 'profit',
 'dip',
 'at',
 'warner',
 'bros',
 ',',
 'and',
 'less',
 'users',
 'for',
 'aol',
 '.',
 'time',
 'warner',
 'said',
 'on',
 'friday',
 'that',
 'it',
 'now',
 'owns',
 '8',
 '%',
 'of',
 'sear

In [12]:
tokens[513]

['richard',
 'and',
 'judy',
 'choose',
 'top',
 'books',
 'the',
 '10',
 'authors',
 'shortlisted',
 'for',
 'a',
 'richard',
 'and',
 'judy',
 'book',
 'award',
 'in',
 '2005',
 'are',
 'hoping',
 'for',
 'a',
 'boost',
 'in',
 'sales',
 'following',
 'the',
 'success',
 'of',
 'this',
 'year',
 "'s",
 'winner',
 '.',
 'the',
 'tv',
 'couple',
 "'s",
 'interest',
 'in',
 'the',
 'book',
 'world',
 'coined',
 'the',
 'term',
 '``',
 'the',
 'richard',
 '&',
 'judy',
 'effect',
 "''",
 'and',
 'created',
 'the',
 'top',
 'two',
 'best-selling',
 'paperbacks',
 'of',
 '2004',
 'so',
 'far',
 '.',
 'the',
 'finalists',
 'for',
 '2005',
 'include',
 'andrew',
 'taylor',
 "'s",
 'the',
 'american',
 'boy',
 'and',
 'robbie',
 'williams',
 "'",
 'autobiography',
 'feel',
 '.',
 'this',
 'year',
 "'s",
 'winner',
 ',',
 'alice',
 'sebold',
 "'s",
 'the',
 'lovely',
 'bones',
 ',',
 'sold',
 'over',
 'one',
 'million',
 '.',
 'joseph',
 "o'connor",
 "'s",
 'star',
 'of',
 'the',
 'sea',
 'cam

# **Stop Word Removal**

In [13]:
from nltk.corpus import stopwords

In [14]:
stop_words = set(stopwords.words('english'))

In [15]:
sw_rem=[]

In [16]:
for i in range(514):
    sw_rem.append([ j for j in tokens[i] if not j.lower() in stop_words ])

In [17]:
sw_rem[0]

['ad',
 'sales',
 'boost',
 'time',
 'warner',
 'profit',
 'quarterly',
 'profits',
 'us',
 'media',
 'giant',
 'timewarner',
 'jumped',
 '76',
 '%',
 '$',
 '1.13bn',
 '(',
 '£600m',
 ')',
 'three',
 'months',
 'december',
 ',',
 '$',
 '639m',
 'year-earlier',
 '.',
 'firm',
 ',',
 'one',
 'biggest',
 'investors',
 'google',
 ',',
 'benefited',
 'sales',
 'high-speed',
 'internet',
 'connections',
 'higher',
 'advert',
 'sales',
 '.',
 'timewarner',
 'said',
 'fourth',
 'quarter',
 'sales',
 'rose',
 '2',
 '%',
 '$',
 '11.1bn',
 '$',
 '10.9bn',
 '.',
 'profits',
 'buoyed',
 'one-off',
 'gains',
 'offset',
 'profit',
 'dip',
 'warner',
 'bros',
 ',',
 'less',
 'users',
 'aol',
 '.',
 'time',
 'warner',
 'said',
 'friday',
 'owns',
 '8',
 '%',
 'search-engine',
 'google',
 '.',
 'internet',
 'business',
 ',',
 'aol',
 ',',
 'mixed',
 'fortunes',
 '.',
 'lost',
 '464,000',
 'subscribers',
 'fourth',
 'quarter',
 'profits',
 'lower',
 'preceding',
 'three',
 'quarters',
 '.',
 'however',
 

In [18]:
sw_rem[8]

['ethiopia',
 "'s",
 'crop',
 'production',
 '24',
 '%',
 'ethiopia',
 'produced',
 '14.27',
 'million',
 'tonnes',
 'crops',
 '2004',
 ',',
 '24',
 '%',
 'higher',
 '2003',
 '21',
 '%',
 'average',
 'past',
 'five',
 'years',
 ',',
 'report',
 'says',
 '.',
 '2003',
 ',',
 'crop',
 'production',
 'totalled',
 '11.49',
 'million',
 'tonnes',
 ',',
 'joint',
 'report',
 'food',
 'agriculture',
 'organisation',
 'world',
 'food',
 'programme',
 'said',
 '.',
 'good',
 'rains',
 ',',
 'increased',
 'use',
 'fertilizers',
 'improved',
 'seeds',
 'contributed',
 'rise',
 'production',
 '.',
 'nevertheless',
 ',',
 '2.2',
 'million',
 'ethiopians',
 'still',
 'need',
 'emergency',
 'assistance',
 '.',
 'report',
 'calculated',
 'emergency',
 'food',
 'requirements',
 '2005',
 '387,500',
 'tonnes',
 '.',
 'top',
 ',',
 '89,000',
 'tonnes',
 'fortified',
 'blended',
 'food',
 'vegetable',
 'oil',
 '``',
 'targeted',
 'supplementary',
 'food',
 'distributions',
 'survival',
 'programme',
 'chil

## Stemming

In [19]:
from nltk.stem.porter import *
from nltk.stem.snowball import SnowballStemmer
#from nltk.stem import PorterStemmer , LancasterStemmer
from nltk.stem import WordNetLemmatizer

In [20]:
ss = SnowballStemmer(language='english')
#ps = PorterStemmer()
#ls = LancasterStemmer()

In [21]:
result=[]

In [22]:
punctuations = "?:!.,;"
for i in range(514):
    result.append([word for word in sw_rem[i] if word not in punctuations])

In [23]:
result[0]

['ad',
 'sales',
 'boost',
 'time',
 'warner',
 'profit',
 'quarterly',
 'profits',
 'us',
 'media',
 'giant',
 'timewarner',
 'jumped',
 '76',
 '%',
 '$',
 '1.13bn',
 '(',
 '£600m',
 ')',
 'three',
 'months',
 'december',
 '$',
 '639m',
 'year-earlier',
 'firm',
 'one',
 'biggest',
 'investors',
 'google',
 'benefited',
 'sales',
 'high-speed',
 'internet',
 'connections',
 'higher',
 'advert',
 'sales',
 'timewarner',
 'said',
 'fourth',
 'quarter',
 'sales',
 'rose',
 '2',
 '%',
 '$',
 '11.1bn',
 '$',
 '10.9bn',
 'profits',
 'buoyed',
 'one-off',
 'gains',
 'offset',
 'profit',
 'dip',
 'warner',
 'bros',
 'less',
 'users',
 'aol',
 'time',
 'warner',
 'said',
 'friday',
 'owns',
 '8',
 '%',
 'search-engine',
 'google',
 'internet',
 'business',
 'aol',
 'mixed',
 'fortunes',
 'lost',
 '464,000',
 'subscribers',
 'fourth',
 'quarter',
 'profits',
 'lower',
 'preceding',
 'three',
 'quarters',
 'however',
 'company',
 'said',
 'aol',
 "'s",
 'underlying',
 'profit',
 'exceptional',
 

In [24]:
result[8]

['ethiopia',
 "'s",
 'crop',
 'production',
 '24',
 '%',
 'ethiopia',
 'produced',
 '14.27',
 'million',
 'tonnes',
 'crops',
 '2004',
 '24',
 '%',
 'higher',
 '2003',
 '21',
 '%',
 'average',
 'past',
 'five',
 'years',
 'report',
 'says',
 '2003',
 'crop',
 'production',
 'totalled',
 '11.49',
 'million',
 'tonnes',
 'joint',
 'report',
 'food',
 'agriculture',
 'organisation',
 'world',
 'food',
 'programme',
 'said',
 'good',
 'rains',
 'increased',
 'use',
 'fertilizers',
 'improved',
 'seeds',
 'contributed',
 'rise',
 'production',
 'nevertheless',
 '2.2',
 'million',
 'ethiopians',
 'still',
 'need',
 'emergency',
 'assistance',
 'report',
 'calculated',
 'emergency',
 'food',
 'requirements',
 '2005',
 '387,500',
 'tonnes',
 'top',
 '89,000',
 'tonnes',
 'fortified',
 'blended',
 'food',
 'vegetable',
 'oil',
 '``',
 'targeted',
 'supplementary',
 'food',
 'distributions',
 'survival',
 'programme',
 'children',
 'five',
 'pregnant',
 'lactating',
 'women',
 "''",
 'needed',
 

In [25]:
s_stem = []
#p_stem = []
#l_stem = []

In [26]:
for i in range(514):
    #print(f'i = {i}')
  #count = 0
    s = []
    for word in result[i]:
        s.append(ss.stem(word))
    s_stem.append(s)
  #count+=1
  #if count%100 == 0:
    #print(f'count = {count}')
  #p_stem.append([ps.stem(word) for word in sw_rem[i]])
  #l_stem.append([ls.stem(word) for word in sw_rem[i]])

In [27]:
s_stem[0]

['ad',
 'sale',
 'boost',
 'time',
 'warner',
 'profit',
 'quarter',
 'profit',
 'us',
 'media',
 'giant',
 'timewarn',
 'jump',
 '76',
 '%',
 '$',
 '1.13bn',
 '(',
 '£600m',
 ')',
 'three',
 'month',
 'decemb',
 '$',
 '639m',
 'year-earli',
 'firm',
 'one',
 'biggest',
 'investor',
 'googl',
 'benefit',
 'sale',
 'high-spe',
 'internet',
 'connect',
 'higher',
 'advert',
 'sale',
 'timewarn',
 'said',
 'fourth',
 'quarter',
 'sale',
 'rose',
 '2',
 '%',
 '$',
 '11.1bn',
 '$',
 '10.9bn',
 'profit',
 'buoy',
 'one-off',
 'gain',
 'offset',
 'profit',
 'dip',
 'warner',
 'bros',
 'less',
 'user',
 'aol',
 'time',
 'warner',
 'said',
 'friday',
 'own',
 '8',
 '%',
 'search-engin',
 'googl',
 'internet',
 'busi',
 'aol',
 'mix',
 'fortun',
 'lost',
 '464,000',
 'subscrib',
 'fourth',
 'quarter',
 'profit',
 'lower',
 'preced',
 'three',
 'quarter',
 'howev',
 'compani',
 'said',
 'aol',
 "'s",
 'under',
 'profit',
 'except',
 'item',
 'rose',
 '8',
 '%',
 'back',
 'stronger',
 'internet',


In [28]:
s_stem[8]

['ethiopia',
 "'s",
 'crop',
 'product',
 '24',
 '%',
 'ethiopia',
 'produc',
 '14.27',
 'million',
 'tonn',
 'crop',
 '2004',
 '24',
 '%',
 'higher',
 '2003',
 '21',
 '%',
 'averag',
 'past',
 'five',
 'year',
 'report',
 'say',
 '2003',
 'crop',
 'product',
 'total',
 '11.49',
 'million',
 'tonn',
 'joint',
 'report',
 'food',
 'agricultur',
 'organis',
 'world',
 'food',
 'programm',
 'said',
 'good',
 'rain',
 'increas',
 'use',
 'fertil',
 'improv',
 'seed',
 'contribut',
 'rise',
 'product',
 'nevertheless',
 '2.2',
 'million',
 'ethiopian',
 'still',
 'need',
 'emerg',
 'assist',
 'report',
 'calcul',
 'emerg',
 'food',
 'requir',
 '2005',
 '387,500',
 'tonn',
 'top',
 '89,000',
 'tonn',
 'fortifi',
 'blend',
 'food',
 'veget',
 'oil',
 '``',
 'target',
 'supplementari',
 'food',
 'distribut',
 'surviv',
 'programm',
 'children',
 'five',
 'pregnant',
 'lactat',
 'women',
 "''",
 'need',
 'eastern',
 'southern',
 'ethiopia',
 'prolong',
 'drought',
 'kill',
 'crop',
 'drain',
 '

### **Term Document Matrix**

In [29]:
Terms = set()

In [30]:
for i in range(514):
    Terms=Terms.union({term for term in s_stem[i]})

In [31]:
Terms

{'weapon',
 'allay',
 'worldwid',
 'jilt',
 '£548m',
 'repair',
 'grandchild',
 'benmosch',
 'pitch',
 'sheffield-bas',
 'tankan',
 'butan',
 'fierc',
 'perform',
 'confront',
 'duckl',
 '420',
 'azim',
 'ready-mix',
 'door',
 '5.11',
 'cl',
 'exchange-list',
 '14.1bn',
 '£82.7m',
 'stamp',
 'enough',
 '3.24',
 'basic',
 'bcc',
 '42',
 '£140bn',
 'subdu',
 '71.5m',
 'honorari',
 'outsid',
 'given',
 'demonstr',
 'career',
 'deccan',
 'current',
 'durham',
 'babacan',
 'barot',
 'india-pakistan',
 'mr',
 'nigerian-own',
 '767',
 'equal',
 '40-40.25',
 'indiffer',
 'obscur',
 '445.1bn',
 'pre-sal',
 'astronom',
 'happi',
 'unsuccess',
 '4.0',
 '2.4',
 'refer',
 'congruent',
 'top-up',
 'avalanch',
 '42.30',
 'meet',
 'reconstruct',
 'nop',
 'chariti',
 'catwoman',
 'aksoy',
 '£10,000',
 'amex',
 'misus',
 'wittig',
 'expos',
 'gas-guzzl',
 '220bn',
 'britannia',
 'leagu',
 'dove',
 'judi',
 'year-ago',
 'effort',
 'ann',
 'els',
 'joshua',
 'waterborn',
 '1,300',
 '262',
 'report',
 'sho

In [32]:
doc_term_matrix = {}

In [33]:
for term in Terms:
    doc_term_matrix[term] = []
    for i in range(514):
        if term in s_stem[i]: 
            doc_term_matrix[term].append(1)
        else: 
            doc_term_matrix[term].append(0)

**Queries**

In [34]:
import numpy as np

In [35]:
query = input("Enter your query\n")

Enter your query
winner match


In [36]:
def preprocess(query):
    tokens_ = word_tokenize(query)
    sw_rem_ = [ word for word in tokens_ if not word.lower() in stop_words ]
    res = [word for word in sw_rem_ if word not in punctuations]
    stem = [ss.stem(word) for word in res]
    return stem

In [37]:
query_list = preprocess(query)
print(query_list)
v = np.ones((514,), dtype = np.int8)

['winner', 'match']


In [38]:
for word in query_list:
    print(word)
    #print(doc_term_matrix[word])
    arr = np.array(doc_term_matrix[word])
    v = v & arr

#print(f'v = {v}')
print(np.argwhere(v == 1).reshape(1,-1))

winner
match
[[312]]


In [60]:
v = np.zeros((514,), dtype = np.int8)
for word in query_list:
    print(word)
    #print(doc_term_matrix[word])
    arr = np.array(doc_term_matrix[word])
    v = v | arr
    
print(np.argwhere(v == 1).reshape(1,-1))

winner
match
[[ 28  87 128 223 260 270 289 293 312 313 317 384 394 437 460 513]]


### **Inverted Index**

We will use the variable "Terms" for unique terms as previous

In [40]:
inverted_index = {}

for i in range(514):
    for term in s_stem[i]:
        if term in inverted_index:
            inverted_index[term].add(i)
        else: inverted_index[term] = {i}

In [41]:
inverted_index

{'ad': {0,
  6,
  10,
  13,
  14,
  18,
  20,
  28,
  29,
  32,
  34,
  40,
  44,
  46,
  49,
  51,
  52,
  54,
  60,
  61,
  62,
  64,
  68,
  79,
  80,
  85,
  92,
  98,
  99,
  103,
  104,
  105,
  111,
  115,
  116,
  117,
  119,
  120,
  125,
  130,
  132,
  133,
  137,
  139,
  142,
  150,
  151,
  174,
  175,
  176,
  179,
  183,
  188,
  193,
  194,
  197,
  200,
  205,
  206,
  207,
  216,
  218,
  220,
  230,
  240,
  251,
  252,
  254,
  262,
  272,
  274,
  278,
  280,
  285,
  289,
  291,
  295,
  298,
  300,
  302,
  306,
  309,
  316,
  322,
  323,
  327,
  328,
  333,
  347,
  356,
  358,
  359,
  361,
  362,
  365,
  366,
  372,
  373,
  375,
  376,
  378,
  379,
  385,
  386,
  391,
  399,
  400,
  401,
  402,
  405,
  413,
  415,
  420,
  424,
  432,
  433,
  437,
  442,
  445,
  447,
  448,
  449,
  452,
  455,
  461,
  462,
  465,
  468,
  470,
  478,
  492,
  500,
  504},
 'sale': {0,
  2,
  3,
  10,
  12,
  13,
  15,
  24,
  25,
  26,
  37,
  38,
  39,
  48,
  49

In [42]:
p = inverted_index[query_list[0]]
for word in query_list:
    print(word)
    arr = inverted_index[word]
    p = p & arr
    
print(p)

winner
match
{312}


In [43]:
p = inverted_index[query_list[0]]
for word in query_list:
    print(word)
    arr = inverted_index[word]
    p = p | arr
    
print(p)
#[[ 28  87 128 223 260 270 289 293 312 313 317 384 394 437 460 513]] for query 'winner match'

winner
match
{128, 384, 513, 289, 260, 293, 394, 460, 270, 437, 87, 312, 313, 28, 317, 223}


### **TF-IDF**

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [45]:
vectorizer = TfidfVectorizer(stop_words = list(stop_words))

In [46]:
tfidf = vectorizer.fit_transform(docs)

**Calculate similarities between documents**

In [47]:
similarities = np.zeros((514,514))

In [48]:
for i in range(514):
    for j in range(514):
        similarities[i,j] = cosine_similarity(tfidf[i],tfidf[j])

In [49]:
similarities_df = pd.DataFrame(similarities)

In [50]:
similarities_df

0         1         2         3         4         5         6    \
0    1.000000  0.045629  0.032251  0.103438  0.020714  0.031459  0.039132   
1    0.045629  1.000000  0.026308  0.031934  0.019340  0.064035  0.086554   
2    0.032251  0.026308  1.000000  0.009111  0.016373  0.010390  0.013641   
3    0.103438  0.031934  0.009111  1.000000  0.013572  0.041097  0.048955   
4    0.020714  0.019340  0.016373  0.013572  1.000000  0.009291  0.012805   
..        ...       ...       ...       ...       ...       ...       ...   
509  0.017047  0.020313  0.044025  0.005462  0.043890  0.006713  0.034978   
510  0.007207  0.007048  0.004043  0.008027  0.005525  0.005965  0.003106   
511  0.006170  0.024276  0.007479  0.006623  0.005940  0.009517  0.018118   
512  0.033280  0.008499  0.009297  0.013036  0.002975  0.004391  0.003960   
513  0.064797  0.012071  0.009161  0.032609  0.018462  0.008931  0.024409   

          7         8         9    ...       504       505       506  \
0    0.027271  0.019393  0.023407  ...  0.027441  0.022715  0.071938   
1    0.158628  0.006823  0.048898  ...  0.104738  0.030443  0.067401   
2    0.015395  0.023704  0.038382  ...  0.017722  0.017880  0.034457   
3    0.036632  0.019687  0.011211  ...  0.020203  0.028549  0.062856   
4    0.015569  0.065319  0.009998  ...  0.010031  0.013418  0.021411   
..        ...       ...       ...  ...       ...       ...       ...   
509  0.016081  0.009244  0.019222  ...  0.018254  0.007593  0.009879   
510  0.012383  0.007940  0.007154  ...  0.009840  0.003138  0.026891   
511  0.006786  0.002782  0.006068  ...  0.010001  0.005702  0.016992   
512  0.017213  0.004811  0.013660  ...  0.008962  0.021659  0.020158   
513  0.027860  0.019765  0.001487  ...  0.023725  0.016445  0.043316   

          507       508       509       510       511       512       513  
0    0.029252  0.041880  0.017047  0.007207  0.006170  0.033280  0.064797  
1    0.031686  0.051968  0.020313  0.007048  0.024276  0.008499  0.012071  
2    0.038063  0.006077  0.044025  0.004043  0.007479  0.009297  0.009161  
3    0.024734  0.046069  0.005462  0.008027  0.006623  0.013036  0.032609  
4    0.016384  0.027662  0.043890  0.005525  0.005940  0.002975  0.018462  
..        ...       ...       ...       ...       ...       ...       ...  
509  0.019245  0.013498  1.000000  0.001377  0.039012  0.016362  0.005032  
510  0.010248  0.016512  0.001377  1.000000  0.007677  0.006351  0.028091  
511  0.006528  0.013754  0.039012  0.007677  1.000000  0.014487  0.022104  
512  0.007550  0.014663  0.016362  0.006351  0.014487  1.000000  0.023312  
513  0.058762  0.020930  0.005032  0.028091  0.022104  0.023312  1.000000  

[514 rows x 514 columns]

**Query Handling**

In [51]:
query = input("What are you searching for?")

What are you searching for?winner match


In [52]:
query_tfidf = vectorizer.transform([query])

In [53]:
cosineSimilarities = cosine_similarity(query_tfidf, tfidf).flatten()

In [54]:
cosineSimilarities

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04061484, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [55]:
top_res = cosineSimilarities[cosineSimilarities > 0.1]

In [56]:
top_res

array([0.10741961])

In [57]:
rankings = np.argsort(cosineSimilarities)[::-1]

In [58]:
rankings

array([513, 128, 394, 313, 312, 317,  28, 293, 270, 223, 173, 172, 171,
       170, 168, 169, 175, 167, 166, 165, 164, 174, 177, 176, 162, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 163, 160,
       161, 145, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 146, 191, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 190,   1, 192, 222, 225, 226, 227, 228, 229,
       230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
       243, 244, 245, 246, 247, 248, 249, 250, 251, 224, 221, 193, 220,
       130, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
       206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
       219, 131, 129,   2,  49,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  50,  34,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  35,  33,  65,  16,   3,   4,
         5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  1

In [59]:
print(f"Relavent documents are {rankings[:len(top_res)]}")

Relavent documents are [513]
